### ISSUE TITLE
address coordinates in 'wrong' projection format

### ISSUE THREAD

**Issue by rlzijdeman** [ivozandhuis/reuseDeVries#1]
Hi Ivo,

Data points for house addresses in Druid/ivotemp-HISGIS are in EPSG 28992 (Amersfoort New) where WGS84 is expected by Druid (and W3C). Is it possible for you to update this? In order for sparql queries to directly show the housing properly?

Best,

Richard

**Comment by ivozandhuis** [comment]
Solved.
